MODULE PARTICLES
USE Precision
  IMPLICIT NONE
  INTEGER, DIMENSION(:), ALLOCATABLE:: species
  REAL(dp), DIMENSION(:), ALLOCATABLE:: mass
  REAL(dp), DIMENSION(:), ALLOCATABLE:: x,y,z
  REAL(dp), DIMENSION(:), ALLOCATABLE:: vx,vy,vz
  REAL(dp), DIMENSION(:), ALLOCATABLE:: omegax,omegay,omegaz
  INTEGER::npart
  INTEGER, PARAMETER:: nspecies=2
  INTEGER, DIMENSION(nspecies):: np
END MODULE PARTICLES
